// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    AuthLayout: typeof import('./../application/layouts/AuthLayout.vue')['default']
    Avatar: typeof import('./../application/components/core/Avatar.vue')['default']
    BaseEditor: typeof import('./../application/components/core/editors/BaseEditor.vue')['default']
    BlockLoading: typeof import('./../application/components/core/loading/BlockLoading.vue')['default']
    DefaultLayout: typeof import('./../application/layouts/DefaultLayout.vue')['default']
    DisplayError: typeof import('./../application/components/core/text/DisplayError.vue')['default']
    DisplayHtml: typeof import('./../application/components/core/text/DisplayHtml.vue')['default']
    DonutChart: typeof import('./../application/components/core/DonutChart.vue')['default']
    DoubleClick: typeof import('./../application/components/core/gestures/DoubleClick.vue')['default']
    EmptyAnswers: typeof import('./../application/components/core/empty/EmptyAnswers.vue')['default']
    EmptyData: typeof import('./../application/components/core/empty/EmptyData.vue')['default']
    EmptyFiles: typeof import('./../application/components/core/empty/EmptyFiles.vue')['default']
    EmptySearch: typeof import('./../application/components/core/empty/EmptySearch.vue')['default']
    EmptyState: typeof import('./../application/components/core/empty/EmptyState.vue')['default']
    EmptyTests: typeof import('./../application/components/core/empty/EmptyTests.vue')['default']
    EmptyUserAnswers: typeof import('./../application/components/core/empty/EmptyUserAnswers.vue')['default']
    EmptyUserFlashCards: typeof import('./../application/components/core/empty/EmptyUserFlashCards.vue')['default']
    EmptyUserNotes: typeof import('./../application/components/core/empty/EmptyUserNotes.vue')['default']
    EmptyUserQuestions: typeof import('./../application/components/core/empty/EmptyUserQuestions.vue')['default']
    FileInput: typeof import('./../application/components/core/forms/FileInput.vue')['default']
    Gallery: typeof import('./../application/components/core/media/Gallery.vue')['default']
    HomeLayout: typeof import('./../application/layouts/HomeLayout.vue')['default']
    LoadMore: typeof import('./../application/components/core/LoadMore.vue')['default']
    Logo: typeof import('./../application/components/core/Logo.vue')['default']
    Modal: typeof import('./../application/components/core/modals/Modal.vue')['default']
    Modals: typeof import('./../application/components/core/modals/Modals.vue')['default']
    NotFound: typeof import('./../application/components/core/empty/NotFound.vue')['default']
    OnboardingLayout: typeof import('./../application/layouts/OnboardingLayout.vue')['default']
    PageLoading: typeof import('./../application/components/core/loading/PageLoading.vue')['default']
    PdfReader: typeof import('./../application/components/core/media/PdfReader.vue')['default']
    PhoneInput: typeof import('./../application/components/core/forms/PhoneInput.vue')['default']
    Popover: typeof import('./../application/components/core/modals/Popover.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    Share: typeof import('./../application/components/core/Share.vue')['default']
    SpinLoading: typeof import('./../application/components/core/loading/SpinLoading.vue')['default']
    SuggestedActions: typeof import('./../application/components/core/SuggestedActions.vue')['default']
    Swipe: typeof import('./../application/components/core/gestures/Swipe.vue')['default']
    Tag: typeof import('./../application/components/core/Tag.vue')['default']
    UserName: typeof import('./../application/components/core/UserName.vue')['default']
  }
}
