// THIS FILE IS AUTO GENERATED

export enum IconNames {
  'admin' = 'admin',
  'app-outline' = 'app-outline',
  'app' = 'app',
  'arrow-left' = 'arrow-left',
  'arrow-right' = 'arrow-right',
  'bell-outline' = 'bell-outline',
  'bell' = 'bell',
  'chat-outline' = 'chat-outline',
  'chat' = 'chat',
  'class' = 'class',
  'close-thin' = 'close-thin',
  'close' = 'close',
  'create-outline' = 'create-outline',
  'create' = 'create',
  'e-wallet' = 'e-wallet',
  'equal-to' = 'equal-to',
  'filter' = 'filter',
  'hamburger' = 'hamburger',
  'home-outline' = 'home-outline',
  'home' = 'home',
  'logo' = 'logo',
  'logout' = 'logout',
  'questions' = 'questions',
  'right-nav' = 'right-nav',
  'schedule' = 'schedule',
  'search' = 'search',
  'study' = 'study',
  'tutors' = 'tutors'
}
