name: Publish To Stores

on:
  push:
    tags:
      - 'v*'

jobs:
  build:
    name: Create Release
    environment: production
    runs-on: macos-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Fetch secrets
        env:
          ENV_SECRETS: ${{ secrets.ENV_SECRETS }}
        run: echo "$ENV_SECRETS" > env.json
      - name: Setup Config folder
        env:
          BASE64_ZIPPED_CONTENT: ${{ secrets.BASE64_ZIPPED_CONTENT }}
        run: node bin/unzip.js
      - name: Install Dependencies
        run: yarn
      - name: Setup Project
        run: yarn bin:project:setup
      - name: Version Project
        run: node bin/version.js
        env:
          APP_VERSION: ${{ github.ref }}
      - name: Build Project
        run: yarn build:app
      - run: ls ./
  android:
    name: Publish to Android
    needs: build
    runs-on: macos-latest
    steps:
      - name: Build android
        run: node bin/project appBuild android
      - name: Publish to play store
        run: ls -R ./android/app/build
  ios:
    name: Publish to IOS
    needs: build
    runs-on: macos-latest
    steps:
      - name: Build and push to app store
        run: node bin/project appBuild ios
