name: Publish to GCloud App Engine

on:
  push:
    branches:
      develop

jobs:
  publish-gae:
    environment: develop
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@master
      - name: Fetch secrets
        uses: actions-hub/gcloud@master
        env:
          PROJECT_ID: ${{ secrets.GCLOUD_PROJECT }}
          APPLICATION_CREDENTIALS: ${{ secrets.GCLOUD_AUTH }}
        with:
          args: "secrets versions access latest --secret=Stranerd_Environment_Variables > env.json"
      - name: Create .env File
        run: npm run env:copy:app
      - name: Install Dependencies
        run: yarn
      - name: Build App
        run: yarn build
      - name: Deploy to GAE
        uses: actions-hub/gcloud@master
        env:
          PROJECT_ID: ${{ secrets.GCLOUD_PROJECT }}
          APPLICATION_CREDENTIALS: ${{ secrets.GCLOUD_AUTH }}
        with:
          args: "app deploy --quiet"
