name: Publish to GCloud App Engine

on:
  push:
    branches:
      production

jobs:
  publish-gae:
    environment: production
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@master
      - name: Fetch secrets
        env:
          ENV_SECRETS: ${{ secrets.ENV_SECRETS }}
        run: echo "$ENV_SECRETS" > env.json
      - name: Install Dependencies
        run: yarn
      - name: Setup Project
        run: yarn bin:project:setup --skip-apps
      - name: Build Web
        run: yarn build:web
      - name: Deploy to GAE
        uses: actions-hub/gcloud@master
        env:
          PROJECT_ID: ${{ secrets.GCLOUD_PROJECT }}
          APPLICATION_CREDENTIALS: ${{ secrets.GCLOUD_AUTH }}
        with:
          args: "app deploy --quiet"
